Jacob snotel (#21)
* testing no verify

* explore_snotel.ipynb is for looking at SNOTEL data

* metloom_snotel is for looking at metloom snotel/cdec data

* metloom_snotel_geometry is for using metaearth metloom provider to obtain stations by geometry

* metloom provider

* metloom config changes

* MetloomProvider works for Snotel data

* black

* reformat

* metloom_snotel_geometry demonstrates working example of MetloomProvider

* cdec doesn't have date availability in _get_all_metadata

* cdec _region_to_items does not use datetime, but extract_assets takes care of start/end date so all works out

* style changes

* style changes

* formatting, add metloom library

* combined snotel.yaml and cdec.yaml into metloom.yaml

* class method for points_from_geometry

* remove troublesome notebooks

* reformat explore_snotel.ipynb

* removed empty cell and reformat

* update ipywidgets

* uncertain why notebooks are causing black to fail.

it appears on github the notebooks get trailing commas appended

* removed block comments

* bsd license and save as csv

* exploratory notebook commit

* Test

* added logging info to metloom.py

* metloom example notebook

* attempt to parallelize points_from_geometry.

AttributeError: Can't pickle local object 'SnotelClient.points_from_geometry.<locals>._download_wrapper_fn'

* metloom exploration notebooks

* black metloom.iypnb

* black on notebooks

* update readme with metloom info

* fix notebook from bad format

* notebooks become invaliod jsons

* Added simple multiproc for metloom

* remove troublesome notebooks

* fixed single quotes

* black changes

* fix pandas index

* remove troublesome notebook

* black

* add logger message for no datasets found

* check len(daily_data)

* cdec key error.

should be "Elevation Feet" instead of "ElevationFeet".

Added return_false if there are no assets in collection and aoi.

* rerun test notebook with updated cdec

* rerun notebooks

* columns of search_df

* ElevationFeet or Elevation Feet in columns

* reformat

* passing "all" to assets downloads all assets.

* removed extraneous system config.

* removed extraneous max_down_attempts.

Co-authored-by: Colorado Reed <colorado.j.reed@gmail.com>
Co-authored-by: Raymond Mo <raymondmo@berkeley.com>